### ISSUE TITLE
Guide the user through menu customization.

### ISSUE THREAD

**Issue by aleksei-korolev** [Innoactive/Hub-Tutorial-Unity-Project#17]
Any task that involves controller menu looks like this:
![image](https://user-images.githubusercontent.com/42579543/63353765-8c07a280-c363-11e9-8da2-6b64fcc10c9d.png)

**Comment by LukasReindlGit** [comment]
Unfortunately your feedback feels unspecific and hard for me to work on. It is also persieved as very passive-aggressive.

**Comment by aleksei-korolev** [comment]
Duplicates #14
