### ISSUE TITLE
An important information is hidden behind a long list.

### ISSUE THREAD

**Issue by aleksei-korolev** [Innoactive/Hub-Tutorial-Unity-Project#9]
https://github.com/Innoactive/Hub-Tutorial-Unity-Project#components

> IMPORTANT: Disable [HUB-LOGIN_CHECK] and [HUB-VR-LAUNCHER-CLIENT] for now. We will come back to those later in Chapter 9.

This is actually easy to miss because it looks like a next point in the list.

**Comment by LukasReindlGit** [comment]
In the markdown as well as the pdf it is highlighted red. Github does not support colored text though. Not sure how to make it better

**Comment by LukasReindlGit** [comment]
added bullet points to the components
